### PR TITLE
implementation of cobra CLI 

### PR DESCRIPTION
**Pull request by mattb2401**
Hello, 
Am Matt, I liked your implementation of this framework. As I was going through the code I saw the way you implemented the CLI which was very nice but I thought we could use https://github.com/spf13/cobra to implement a simple yet more robust interface that is more scalable for future implementations.

### CODE REVIEW

**Comment by Shpota** [comment]
Hi Matt,

Thank you for your contribution and your interest in the project. I was initially looking at different CLI implementations, they for sure make things simpler. At the same time, for a library, it is important to keep a minimal number of dependencies, especially when a task can be solved in a simple way. That's why I think we should not introduce cobra or any other third party dependency untill it is really required.

There are other places in the project that require further development. If you are interested we could work together on adding support for more SPA libraries or we can discuss other improvement ideas. 

Let me know what you think.

**Comment by mattb2401** [comment]
Hey Shpota,
I understand, let me look into the project further alternatively you can also direct me where the project needs further development, I am happy to help.

**Comment by Shpota** [comment]
Thanks Matt,

I am out of town for the weekend. I'll be back on Monday and we can discuss further ideas in Gitter https://gitter.im/goxygen/community

Does that work for you?

**Comment by mattb2401** [comment]
Yes this will work. Talk to you then

**Pull request closed without merging**
