### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by maksimov**
Adding a troubleshooting section with an explanation for users of Go 1.13+.

### CODE REVIEW

**Comment by maksimov** [comment]
@Shpota can you have a look, please?

**Comment by Shpota** [comment]
Hi @maksimov. I am sorry for making you wait. 

I think it is enough to mention that Go Modules should be enabled for the versions prior to 1.13. I can be added in the How To section.

**Comment by maksimov** [comment]
Thanks @Shpota. Will just mentioning modules make it clear? I think a person like me - with a mediocre knowledge of Go - would still have to google the error.

**Comment by thesosa** [comment]
I agree this should be added to the README. I came here to see if there was a fix available and found this PR.

**Comment by Shpota** [comment]
Thank you @maksimov, @thesosa. Merged.

**Pull request merged**
